config/routes.rb
AngularjsRails4::Application.routes.draw do
  devise_for :users

  root 'app#index'

  

  scope module: :api , defaults: {format: :json} do
    namespace :v1 do
      resources :pet, only: [:index, :show, :create, :update, :destroy]
    end
  end

  resources :report
  resources :animal_category

  get 's3_service' => 'app#s3_access_token'

end

app/models/animal_category.rb
class AnimalCategory < ActiveRecord::Base



end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :pet
  validates_presence_of :url
end

app/models/owner.rb
class Owner < ActiveRecord::Base

  has_many :pets
  has_many :reports
  belongs_to :user
  validates_presence_of :email, :name



end

app/models/pet.rb
class Pet < ActiveRecord::Base

  belongs_to :owner
  belongs_to :image
  belongs_to :animal_category
  has_many :reports
  belongs_to :place

  scope :lost, -> { where(name: 'chana')}

  validates :name, presence: true
  validates :owner, presence: true
  validates :comments, presence: true
  validates :animal_category, presence: true
  validates :image, presence: true


  # def place
  #   Place.find(place_id)
  # end

  def image_url
    Image.find(image_id).url
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :place_category

  geocoded_by :address
  after_validation :geocode

end

app/models/place_category.rb
class PlaceCategory < ActiveRecord::Base
  has_many :places

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :pet
  belongs_to :owner
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/animal_category_controller.rb
class AnimalCategoryController < ApplicationController

  def index
    @animal_category = AnimalCategory.all
    respond_to do |format|
      format.json { render json: @animal_category, root: false}
    end
  end
  def show
    @animal_category = AnimalCategory.find(params[:id])
    respond_to do |format|
      format.json { render json:@animal_category , root: false}
    end
  end

end

app/controllers/api/pet_controller.rb
class Api::PetController < ApiController

  def index
    @pet = Pet.all
    respond_to do |format|
      format.json { render json: @pet , root: false}
    end
  end

  def show
    @pet = Pet.find(params[:id])
    respond_to do |format|
      format.json { render json: @pet }
    end
  end

  def create

    @pet = Pet.new(pet_params)

    if @pet.save
      render
    else
      render json: {
          message: 'Validation Failed',
          errors: @pet.errors.full_messages
      }, status: 442
    end

  end

  def destroy
    Pet.find(params[:id]).destroy
    head :ok
  end

  private

  def pet_params
    {
      name: params[:name],
      comments: params[:comments],
      reported_as: params[:reported_as],
      image_id: image_id,
      owner: owner,
    }
  end

  def image_url
    Image.where(:id => @pet.image_id )
  end

  def owner

    Owner.find_or_create_by(name: params[:name])

  end




end

app/controllers/api/v1/pet_controller.rb
class Api::V1::PetController < ApiController

  def index
    if  params[:name]
      @pet = Pet.where(:name => params[:name] )
    else
      @pet = Pet.all
    end

    respond_to do |format|
      format.json { render json: @pet , root: false}
    end
  end

  def show
    @pet = Pet.find(params[:id])
    respond_to do |format|
      format.json { render json: @pet }
    end
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      format.json { render json: @pet, status: 201  }
    else
      render json: {
          message: 'Error while saving pet',
          errors: @pet.errors.full_messages
      }, status: 442
    end

  end

  def sort
    parameter = params["sort"]
    Pet.where("DESC by", parameter)

  end

  def destroy
    Pet.find(params[:id]).destroy
    head :ok
  end

  private

  def pet_params
    {
      name: params[:name],
      comments: params[:comments],
      image: params[:image],
      place: params[:place],
      owner: params[:owner],
    }
  end

  def image_url
    Image.find(@pet.image_url)
  end

  def owner
    Owner.find_or_create_by(name: params[:name])
  end


end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/app_controller.rb
class AppController < ApplicationController

  def index
    @place = Place.first
  end

  def s3_access_token
    render json: {
        policy:    s3_upload_policy,
        signature: s3_upload_signature,
        key:        ENV['AWS_ACCESS_KEY_ID'],
    }
  end

  protected

  def s3_upload_policy
    @policy ||= create_s3_upload_policy
  end

  def create_s3_upload_policy
    Base64.encode64(
        {
            "expiration" => 1.hour.from_now.utc.xmlschema,
            "conditions" => [
                { "bucket" =>  ENV['S3_BUCKET'] },
                [ "starts-with", "$key", "" ],
                { "acl" => "public-read" },
                [ "starts-with", "$Content-Type", "" ],
                [ "content-length-range", 0, 10 * 1024 * 1024 ]
            ]
        }.to_json).gsub(/\n/,'')
  end

  def s3_upload_signature
    Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'), ENV['AWS_SECRET_ACCESS_KEY'] , s3_upload_policy)).gsub("\n","")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/report_controller.rb
class ReportController < ApplicationController

  def index
  end

  def new
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
    @form_data = @s3_direct_post.fields.to_json
    @s3_direct_post
  end

end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# app/helpers/application_helper.rb
# # Render a partial into a script tag so Angular
# # sticks it into $templateCache
  def load_ng_template(partial)
    content_tag :script, type: 'text/ng-template', id: "#{partial}.html", controller: "findMyDogApp" do
      render partial
    end
  end
end

app/views/app/_main_menu.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'Principal' , root_path %>

      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>
  <section class="top-bar-section">

    <ul class="right">
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#">Main Item 1</a>
        <ul class="dropdown">
          <li><label>Section Name</label></li>
          <li class="has-dropdown">
            <a href="#" class="">Has Dropdown, Level 1</a>
            <ul class="dropdown">
              <li><a href="#">Dropdown Options</a></li>
              <li><a href="#">Dropdown Options</a></li>
              <li><a href="#">Level 2</a></li>
              <li><a href="#">Subdropdown Option</a></li>
              <li><a href="#">Subdropdown Option</a></li>
              <li><a href="#">Subdropdown Option</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Option</a></li>
          <li><a href="#">Dropdown Option</a></li>
          <li class="divider"></li>
          <li><label>Section Name</label></li>
          <li><a href="#">Dropdown Option</a></li>
          <li><a href="#">Dropdown Option</a></li>
          <li><a href="#">Dropdown Option</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% else %>
          <%= link_to('Login', new_user_session_path)  %>
      <% end %>
      </li>
      <li class="divider"></li>
      <li class="has-dropdown">
        <a href="#">Admin</a>
        <ul class="dropdown">
          <li><a href="#">Dropdown Option</a></li>
          <li><a href="#">Dropdown Option</a></li>
          <li><a href="#">Dropdown Option</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/app/_results_map.html.slim
//input type='checkbox' name="show_boxes" ng-model='show_map_pet_boxes'
p
  |{{show_map_pet_boxes}}
google-map zoom='map.zoom' center='map.center' draggable="true" options="options" refresh='perform_refresh()'
  markers fit="true"
    marker ng-repeat="pet in pets|orderBy: sortBy|| pet.name" coords="pet.place" idKey='$index' icon='map.icon' click='show($index)'
      window coords='pet.place' show='{{show_map_pet_boxes}}' class="label" click='show($index)'
        img ng-src='{{pet.image_url}}' class="small_round_image"

app/views/app/_search_form.html.slim
div id="search_box"
 div class="row collapse"
   label Afina tu busqueda:
   select
    option value="CP" Codigo Postal
    option value="Ciudad" Ciudad
    option value="Ciudad" Raza
    option value="Ciudad" Color
    input type="text" placeholder="Busqueda"
    div align="center"
     a
       label class=" button small radius centered" Buscar

app/views/app/_small_pet_block.html.slim
div class="small-view"
  img ng-src="{{pet.image_url}}" align="left"
  h2
    |{{pet.name}}
    /  |{{pet.comments}}
  |<strong>Se perdio en:</strong> {{pet.place.name}}<br>
  |<strong>Dueño:</strong>{{pet.owner.name}}<br>
  |<strong>Raza:</strong>{{pet.animal_category.category}}

  h4 class="panel"
    |¿ Encontraste a {{pet.name}} ?

app/views/app/angular/_lost_pet_dialog.html.slim
div class="large-4 column small-view" id="dialog_data"

  img ng-src="{{pet.image_url}}" align="left"
  h2
    |{{pet.name}}
  /  |{{pet.comments}}
  |<strong>Se perdio en:</strong> {{pet.place.name}}<br>
  |<strong>Dueño:</strong>{{pet.owner.name}}<br>
  |<strong>Raza:</strong>{{pet.animal_category.category}}

  h4 class="panel"
    |¿ Encontraste a {{pet.name}} ?

  hr
  ul class="button-group radius"
    li
      a class='button tiny alert'
        =fa_icon "facebook"
      a class='button tiny'
        =fa_icon "envelope-o"
      a class='button tiny'
        =fa_icon "comment"
      a class='button tiny'
        =fa_icon "google-plus-square"


div class="large-4 column"
  div align="right"
    span ng-click="closeModal()"
      =fa_icon "times"
  hr
  dl class="sub-nav top-filtre"
    dt Filtro:
    dd class="active"
      =link_to('Todos','#')
    dd
      =link_to('Perdidos','#')
  google-map zoom='map.zoom + 3' center='pet.place' draggable="false" options="options"
    marker coords="pet.place" icon='map.icon' idKey='$index'
      /#Aqui se puede meter el window
      window show='show'
        img ng-src='{{pet.image_url}}' class="small_round_image"

  div align="center"
    br
    button class="tiny radius success" ng-click="createLostReport()"
      |Lo has visto?
    button class="tiny radius" ng-click="closeModal()"
      |Cerrar

app/views/app/index.html.slim
div ng-controller="indexController"

  / Views
  =load_ng_template('/app/angular/lost_pet_dialog')

  /Filters
  div class="row"
    div class="large-6 small-2 columns"

      h2 class="ciudad" Queretaro
      dl class="sub-nav top-filtre"
        dt Filtro:
        dd class="active"
          =link_to('Todos','#')
        dd
          =link_to('Perdidos','#')
        dd
          =link_to('Localizados','#')
        dd
          =link_to('Perros','#')
        dd
          =link_to('Gatos','#')
        dd
          =link_to('Otros','#')

    div class="large-6 columns"
      hr
      ul class="button-group right"
        li
          a href="#{new_report_path}"
            label class="button alert small radius" ¿Perdiste a tu mascota?
        li
          a href="#{new_report_path}"
            label class="button alert small radius" ¿Encontraste alguna mascota?
      div align='right'
        hr

  /Map
  div class="row" ng-show='renderMap'
    div class="large-12 large-centered columns"
      =render :partial => 'results_map'

  /Results
  div class="row "
    br

    div class="large-3 columns"
      label for="filter" Filtro
      input type='text' name='filter' ng-model='filter'
    div class="large-3 columns   "
      label for='sortby' Ordenar por:
      select class="radius" name='sortby' ng-model="sortby"
        option value='name' selected='selected' Nombre
        option value='animal_category.category' Raza
      /label ng-click='findMe()' find

  div class="row"
    div masonry='' reload-on-show="" column-width="40"
      div ng-repeat="pet in pets| filter:filter | orderBy:sortby" ng-click="show($index)" class="masonry-brick"
        =render :partial => 'small_pet_block'


        /-if user_signed_in?
      /  button class="tiny alert" ng-click="delete($index)" Borrar

app/views/app/menus/_left_menu.html.slim
div class="large-3 columns panel" align="center"

  div align="center"
    div class="first_circle"
    div class="first_div"
      div class="second_div"
        div class="img_div"
          img src="https://s3-us-west-2.amazonaws.com/findmydog/logo4.png"
    div class="txt_welcome"
      h1 PerdiDOG
      h3 class="subheader" Queretaro
    div class="txt_user"
      h5 Ayudamos a los perros perdidos a regresar a casa o encontrar una nueva.
      hr

  div class="row" align="center"
    div class="large-8 large-centered  columns"
      = render :partial => 'app/search_form'

  div class="row"

    h6 Siguenos en:
    div align="center"

      a class='button tiny secondary'
        =fa_icon "facebook"
      a class='button tiny secondary'
        =fa_icon "google-plus-square"


  hr
  div class="button-bar" align="center"
    ul class="button-group center"
      li
        label class="tiny button secondary" Perdidos: 1551
      li
        label class="tiny button alert" Encontrados:202
      li
        label class="tiny button" Cerca de mi:405

  br
  hr
  p
  |En  <strong>PerdiDog </strong> facilitamos la busqueda de mascotas, asi como de los dueños de una mascota a la cual hayas encontrado.
  hr

app/views/app/menus/_main_menu.html.slim
nav class="top-bar" data-topbar=""
  ul class="title-area"
    li class="name"
      h1
        = link_to 'Principal' , root_path
    li class="toggle-topbar menu-icon"
      a href="#"
        span menu
  section class="top-bar-section"

    ul class="right"
      li class="divider"

      li class="has-dropdown"
        a href="#"
          |Preguntas Frequentes
        ul class="dropdown"
          li
            label
              |Precio
          li class="has-dropdown"
            a href="#" class="" Servicios Gratis
            ul class="dropdown"
              li
                a href="#" Servicios premium
              li
                a href="#" Como puedo ayudar?
      li class="divider"
      li class="has-dropdown"
        a href="#" Servicios
        ul class="dropdown"
          li
            label Localizacion
          li class="has-dropdown"
            a href="#" class=""
              |Has Dropdown, Level 1
            ul class="dropdown"
              li
                a href="#"
                  | Dropdown Options
      li class="divider"
      li
        -if user_signed_in?
          =link_to('Logout', destroy_user_session_path, :method  => :delete)
        -else
          =link_to('Login', new_user_session_path)

      -if user_signed_in?
        li class="divider"
        li class="has-dropdown"
          a href="#" Admin
          ul class="dropdown"
            li
              a href="#" Administracion Usarios
            li class="divider"
            li
              a href="#" See all &rarr;

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "PerdiDog" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>

<!--TODO https://github.com/geddski/overmind -->
<body  ngCloak>
<div class="row">
  <%= render :partial => 'app/menus/main_menu' %>
  <%= render :partial => 'app/menus/left_menu' %>
  <div class="large-9 columns">
    <%= yield %>
  </div>
</div>

<footer class="row">
  <div class="large-12 columns">
    <ul class="breadcrumbs">
      <li><a href="/">Principal</a></li>
      <li><a href="/report/new">Reportar perro perdido</a></li>
      <li><a href="/paciente">Localizados</a></li>
      <li class="current"><a href="#">Servicios</a></li>
    </ul>
  </div>
</footer>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "file_upload" %>
</body>
</html>

app/views/report/index.html.slim
div class="row"
  h2 Reporte de mascota extraviada
  h3 Nueva mascota
  =render :partial => 'app/new_lost_report'

app/views/report/new.html.slim
br
br
div class="row" ng-controller='lostReportController'
  div class="large-6 large-centered columns panel radius"
    h2 Reporte de mascota extraviada
    form class='directUpload'
      input type="text" name="name" placeholder="Nombre mascota" ng-model="pet.name"
      div class="row"
        div class="column large-4 small-5"
          input type="text" name="lost_in" placeholder="Lugar donde se perdio"
        div class="column large-4 small-5"
        label class="tiny button radius alert" ng-click="showMap()"
          |mapa
      div class="row" ng-show="step2"
        div class="column large-4 small-5"
          label for="animal" Animal
          select ng-model="animal" name="animal"
            option Perro
            option Gato
            option Vaca
            option Zorro
        div class="column large-4 small-5"
          label for="animal_subcategory"
            |Raza
          select ng-model="pet.animal_subcategory" name="animal_subcategory"
            option Perro
      div class="row" ng-show="step3"
        div class="column large-3 small-1"
          label for="pet_sex" Sexo
          input type='radio' name='pet_sex' Macho
          input type='radio' name='pet_sex' Hembra
      div class="row" ng-show="step4"
        div class="column large-5 small-1"
          label for="fileinput" Subir imagen:
          input type='file' ng-model='fileinput' name='fileinput'

        div class="column large-7"
          img class="upload_image" id='pet_image' src="http://placehold.it/900x540&text=Foto:{{pet.name}}"


      div class="row" ng-show="step5"
        br
        textarea name="comments" placeholder="Comentarios, Señas particulares" ng-model="pet.comment" rows="8" cols="50"
        input type='hidden' name='form_data' id='form_data' value="#{@form_data}"
        input type='hidden' name='url' id='upload_url' value="#{@s3_direct_post.url}"
        input type='hidden' name='host' id='upload_host' value="#{@s3_direct_post.url.host}"
        input type='submit'  class="alert tiny" ng-click='createLostReport()' Generar Reporte
      div class="row"
        div class="column large-2 large-offset-6"
          label class="button alert tiny pull-left"
            =fa_stacked_icon "arrow-circle-right", base: "square-o", text: "Siguiente", class: :panel

  div class="column large-6 large-centered"
    br
    ul
      h5 Te recomendamos:
      li
        |regresar a lugar donde viste por ultima vez a tu mascota
      li
        |dejar agua cerca del lugar

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Ya tienes cuenta?", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrarse", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvidaste tu contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "No recibiste las instrucciones de como confirmar tu cuenta?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "No recibiste las instrucciones de como desbloquear tu cuenta?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar con #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>